export enum ApiRoutes {
  HEALTH_CHECK = "health-check",
  GET_CONVEYOR_BY_NAME = "conveyors?name=",
  GET_CONVEYORS = "conveyors/all",
  GET_CONVEYORS_DATA = "conveyors/all_data",
  GET_PRODUCT_BY_ID = "products",
  GET_ACTIVE_SUMMARY = "summaries/active?conveyor_id=",
  GET_EMPLOYEES_BY_BARCODE = "employees?barcode=",
  CREATE_CONSUMED_MATERIAL = "consumed-materials",
  CREATE_EXTRUSION_ENTRY = "params/extrusion",
  CREATE_VARNISH_ENTRY = "params/varnish",
  CREATE_OFFSET_ENTRY = "params/offset",
  CREATE_SEALANT_ENTRY = "params/sealant",

  CREATE_EXTRUSION_STATUS = "statuses/extrusion",
  CREATE_OFFSET_STATUS = "statuses/offset",
  CREATE_VARNISH_STATUS = "statuses/varnish",
  CREATE_SEALANT_STATUS = "statuses/sealant",

  PRODUCTION_BOX = "production-box",

  GET_RONDELS = "rondels",
  GET_PICTURES = "pictures",
  GET_EXTRUSION_SOP_PICTURES = "sop/extrusion",
  GET_VARNISH_SOP_PICTURES = "sop/varnish",
  GET_OFFSET_SOP_PICTURES = "sop/offset",
  GET_SEALANT_SOP_PICTURES = "sop/sealant",

  GET_EXTRUSION_OPERATIONS = "operations/extrusion",
  GET_VARNISH_OPERATIONS = "operations/varnish",
  GET_OFFSET_OPERATIONS = "operations/offset",
  GET_SEALANT_OPERATIONS = "operations/sealant",
  ZPL = "zpl",
  PRINTER = "printer",

  // GET_SUMMARY_RAW_MATERIALS_BY_SUMMARY_ID = "summary-raw-materials/by_summary_id",

  // GET_ACTIVE_SUMMARY_COUNTERS = "summaries/active_counters",
  // GET_SUMMARY_RAW_MATERIALS_CURRENT = "summary-raw-material-current/get_list",
  // GET_CHIEF_TECHNOLOGIST_NOTE = "chief-technologist-notes/by_summary_id",
  // GET_EXTRUSION_HARDWARE_TRESHOLDS = "extrusion/hardware/get_trehsholds",
  // GET_EXTRUSION_HARDWARE_CURRENT_PARAMS = "extrusion/hardware/get_params",
  // GET_EXTRUSION_HARDWARE_ALL_PARAMS = "extrusion/hardware/get_all_params",
  // CREATE_EXTRUSION_HARDWARE_CURRENT_PARAM = "extrusion/hardware/create_params_record",
  // CREATE_SUMMARY_RAW_MATERIALS_CURRENT = "summary-raw-material-current/create",
  // GET_EXTRUSION_QUALITY_TRESHOLDS = "extrusion/quality_control/get_trehsholds",
  // GET_EXTRUSION_QUALITY_CURRENT_PARAMS = "extrusion/quality_control/get_params",
  // GET_EXTRUSION_QUALITY_ALL_PARAMS = "extrusion/quality_control/get_all_params",
  // CREATE_EXTRUSION_QUALITY_CURRENT_PARAM = "extrusion/quality_control/create_params_record",
}
