export enum ApiRoutes {
  HEALTH_CHECK = "health-check",
  GET_CONVEYOR_BY_NAME = "conveyors?name=",
  GET_CONVEYORS = "conveyors/all",
  GET_CONVEYORS_DATA = "conveyors/all_data",
  GET_PRODUCT_BY_ID = "products",
  GET_ACTIVE_SUMMARY = "summaries/active?conveyor_id=",
  GET_EMPLOYEES_BY_BARCODE = "employees?barcode=",
  CREATE_CONSUMED_MATERIAL = "consumed-materials",
  CREATE_EXTRUSION_ENTRY = "params/extrusion",
  CREATE_VARNISH_ENTRY = "params/varnish",
  CREATE_OFFSET_ENTRY = "params/offset",
  CREATE_SEALANT_ENTRY = "params/sealant",
  CREATE_STATUS = "statuses",
  PRODUCTION_BOX = "production-box",
  GET_PICTURES = "product-picture",
  GET_SOP_PICTURES = "operation-picture",
  // GET_EXTRUSION_SOP_PICTURES = "sop/extrusion",
  // GET_VARNISH_SOP_PICTURES = "sop/varnish",
  // GET_OFFSET_SOP_PICTURES = "sop/offset",
  // GET_SEALANT_SOP_PICTURES = "sop/sealant",
  // GET_EXTRUSION_OPERATIONS = "operations/extrusion",
  // GET_VARNISH_OPERATIONS = "operations/varnish",
  // GET_OFFSET_OPERATIONS = "operations/offset",
  // GET_SEALANT_OPERATIONS = "operations/sealant",
  GET_OPERATIONS = "operations/by_id",
  ZPL = "zpl",
  PRINTER = "printer",
}
