"use client";

import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/shared/lib/utils";
import { ThemeProvider } from "@/features/theme";
import { ServerFalldown } from "@/features/health-check";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function GlobalError({ reset }: { reset: () => void }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "bg-background font-sans antialiased flex flex-col h-dvh",
          fontSans.variable,
        )}
      >
        <ThemeProvider>
          <ServerFalldown reset={reset} isAuto={false} />
        </ThemeProvider>
      </body>
    </html>
  );
}
