import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/shared/lib/utils";
import { AppProvider } from "./_providers/app-provider";
import { getHealthCheck } from "@/features/health-check/api/get-health-check";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await getHealthCheck({ isServer: true });
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "bg-background font-sans antialiased flex flex-col h-dvh ",
          `${geistSans.variable} ${geistMono.variable} antialiased`,
        )}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
