services:
  tubes_api:
    build:
      context: .
      dockerfile: docker/api_tubes/Dockerfile.new
      args:
        - NODE_ENV=production

  public_api:
    build:
      context: .
      dockerfile: docker/public_api/Dockerfile.fast
      args:
        - NODE_ENV=production

  new_app:
    build:
      context: .
      dockerfile: docker/new-app/Dockerfile.new
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - INTERNAL_API_URL=${INTERNAL_API_URL}

  tubes_dash:
    build:
      context: .
      dockerfile: docker/tubes/Dockerfile.new
      args:
        - NODE_ENV=production

  nginx:
    build:
      context: ./docker/nginx
      args:
        - NODE_ENV=production

  nginx-file-server:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile.file-server
      args:
        - NODE_ENV=production
