FROM node:20-alpine AS build-step 

WORKDIR /app

COPY ./tubes_application/package*.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm ci

COPY ./tubes_application/ ./

RUN --mount=type=cache,target=/app/node_modules/.vite \
    npm run build


FROM nginx:stable-alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=build-step /app/dist /usr/share/nginx/html
COPY docker/tubes/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
