FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
COPY tubes_application/package.json ./tubes_application/

RUN npm ci -w tubes_application

COPY tubes_application/ ./tubes_application/

WORKDIR /app/tubes_application
RUN npm run build

FROM nginx:stable-alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/tubes_application/dist /usr/share/nginx/html
COPY docker/tubes/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
