
# user nginx;
# worker_processes auto;
# pid /run/nginx.pid;
# # include /etc/nginx/modules-enabled/*.conf;

# events {
#     worker_connections 1024; 
#     multi_accept on;
# }

# http { 

#     server {
#     listen 3000 default;
    
#     root /usr/share/nginx/html;
#     index index.html;

#     location / {
#         try_files $uri $uri/ /index.html;
#     }

#     include /etc/nginx/mime.types;
    
# }

# }



user nginx;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
    multi_accept on;
}

http {
    # Перенесли сюда для глобального действия
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;

    gzip on;
gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;


    server {
        listen 3000 default_server; # Исправлено: default_server вместо default
        
        root /usr/share/nginx/html;
        index index.html;

        location / {
            # Для SPA: если файл не найден, отдаем index.html
            try_files $uri $uri/ /index.html;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
    expires 1y;
    add_header Cache-Control "public, no-transform";
}


        # Отключаем логи для иконок и роботов, чтобы не забивать диск
        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }
    }
}
