-- CreateTable
CREATE TABLE "tresholds" (
    "id" SERIAL NOT NULL,
    "product_id" INTEGER NOT NULL,
    "conveyor_id" INTEGER NOT NULL,
    "extrusion_press_speed_min" INTEGER NOT NULL,
    "extrusion_press_speed_max" INTEGER NOT NULL,
    "extrusion_blow_time_min" INTEGER NOT NULL,
    "extrusion_blow_time_max" INTEGER NOT NULL,
    "extrusion_turning_machine_speed_min" INTEGER NOT NULL,
    "extrusion_turning_machine_speed_max" INTEGER NOT NULL,
    "extrusion_annealing_furnace_temp_min" INTEGER NOT NULL,
    "extrusion_annealing_furnace_temp_max" INTEGER NOT NULL,
    "extrusion_tube_cilindrical_section_length_min" INTEGER NOT NULL,
    "extrusion_tube_cilindrical_section_length_max" INTEGER NOT NULL,
    "extrusion_membrane_thickness_min" DOUBLE PRECISION NOT NULL,
    "extrusion_membrane_thickness_max" DOUBLE PRECISION NOT NULL,
    "extrusion_tube_diameter_min" DOUBLE PRECISION NOT NULL,
    "extrusion_tube_diameter_max" DOUBLE PRECISION NOT NULL,
    "extrusion_tube_cilindrical_section_thickness_min" DOUBLE PRECISION NOT NULL,
    "extrusion_tube_cilindrical_section_thickness_max" DOUBLE PRECISION NOT NULL,
    "extrusion_tube_rigidity_min" INTEGER NOT NULL,
    "extrusion_tube_rigidity_max" INTEGER NOT NULL,
    "extrusion_external_thread_value" TEXT NOT NULL,
    "varnish_varnish_machine_speed_min" INTEGER NOT NULL,
    "varnish_varnish_machine_speed_max" INTEGER NOT NULL,
    "varnish_total_air_pressure_min" DOUBLE PRECISION NOT NULL,
    "varnish_total_air_pressure_max" DOUBLE PRECISION NOT NULL,
    "varnish_feed_can_air_pressure_min" DOUBLE PRECISION NOT NULL,
    "varnish_feed_can_air_pressure_max" DOUBLE PRECISION NOT NULL,
    "varnish_nozzle_regulator_air_pressure_min" DOUBLE PRECISION NOT NULL,
    "varnish_nozzle_regulator_air_pressure_max" DOUBLE PRECISION NOT NULL,
    "varnish_cells_speed_min" INTEGER NOT NULL,
    "varnish_cells_speed_max" INTEGER NOT NULL,
    "varnish_injection_a_start_position_min" INTEGER NOT NULL,
    "varnish_injection_a_start_position_max" INTEGER NOT NULL,
    "varnish_injection_b_start_position_min" INTEGER NOT NULL,
    "varnish_injection_b_start_position_max" INTEGER NOT NULL,
    "varnish_injection_c_start_position_min" INTEGER NOT NULL,
    "varnish_injection_c_start_position_max" INTEGER NOT NULL,
    "varnish_injection_d_start_position_min" INTEGER NOT NULL,
    "varnish_injection_d_start_position_max" INTEGER NOT NULL,
    "varnish_injection_a_end_position_min" INTEGER NOT NULL,
    "varnish_injection_a_end_position_max" INTEGER NOT NULL,
    "varnish_injection_b_end_position_min" INTEGER NOT NULL,
    "varnish_injection_b_end_position_max" INTEGER NOT NULL,
    "varnish_injection_c_end_position_min" INTEGER NOT NULL,
    "varnish_injection_c_end_position_max" INTEGER NOT NULL,
    "varnish_injection_d_end_position_min" INTEGER NOT NULL,
    "varnish_injection_d_end_position_max" INTEGER NOT NULL,
    "varnish_tube_molding_start_position_min" INTEGER NOT NULL,
    "varnish_tube_molding_start_position_max" INTEGER NOT NULL,
    "varnish_tube_molding_end_position_min" INTEGER NOT NULL,
    "varnish_tube_molding_end_position_max" INTEGER NOT NULL,
    "varnish_polimerization_furnace_temp_min" INTEGER NOT NULL,
    "varnish_polimerization_furnace_temp_max" INTEGER NOT NULL,
    "varnish_internal_varnish_porosity_min" DOUBLE PRECISION NOT NULL,
    "varnish_internal_varnish_porosity_max" DOUBLE PRECISION NOT NULL,
    "offset_printing_machine_speed_min" INTEGER NOT NULL,
    "offset_printing_machine_speed_max" INTEGER NOT NULL,
    "offset_total_air_pressure_min" INTEGER NOT NULL,
    "offset_total_air_pressure_max" INTEGER NOT NULL,
    "offset_padding_furnace_temp_min" INTEGER NOT NULL,
    "offset_padding_furnace_temp_max" INTEGER NOT NULL,
    "offset_offset_furnace_temp_min" INTEGER NOT NULL,
    "offset_offset_furnace_temp_max" INTEGER NOT NULL,
    "offset_printer_motor_min" INTEGER NOT NULL,
    "offset_printer_motor_max" INTEGER NOT NULL,
    "offset_base_covers_holders_motor_min" INTEGER NOT NULL,
    "offset_base_covers_holders_motor_max" INTEGER NOT NULL,
    "offset_base_covers_station_motor_min" INTEGER NOT NULL,
    "offset_base_covers_station_motor_max" INTEGER NOT NULL,
    "offset_imprint_quantity_printed_box_1_min" INTEGER,
    "offset_imprint_quantity_printed_box_1_max" INTEGER,
    "offset_imprint_quantity_printed_box_2_min" INTEGER,
    "offset_imprint_quantity_printed_box_2_max" INTEGER,
    "offset_imprint_quantity_printed_box_3_min" INTEGER,
    "offset_imprint_quantity_printed_box_3_max" INTEGER,
    "offset_imprint_quantity_printed_box_4_min" INTEGER,
    "offset_imprint_quantity_printed_box_4_max" INTEGER,
    "offset_imprint_quantity_printed_box_5_min" INTEGER,
    "offset_imprint_quantity_printed_box_5_max" INTEGER,
    "offset_imprint_quantity_printed_box_6_min" INTEGER,
    "offset_imprint_quantity_printed_box_6_max" INTEGER,
    "offset_ink_supply_time_min" DOUBLE PRECISION NOT NULL,
    "offset_ink_supply_time_max" DOUBLE PRECISION NOT NULL,
    "sealant_cap_machine_speed_min" INTEGER NOT NULL,
    "sealant_cap_machine_speed_max" INTEGER NOT NULL,
    "sealant_total_air_pressure_min" DOUBLE PRECISION NOT NULL,
    "sealant_total_air_pressure_max" DOUBLE PRECISION NOT NULL,
    "sealant_holders_forward_min" INTEGER NOT NULL,
    "sealant_holders_forward_max" INTEGER NOT NULL,
    "sealant_holders_opening_left_min" INTEGER NOT NULL,
    "sealant_holders_opening_left_max" INTEGER NOT NULL,
    "sealant_holders_opening_right_min" INTEGER NOT NULL,
    "sealant_holders_opening_right_max" INTEGER NOT NULL,
    "sealant_holders_closing_min" INTEGER NOT NULL,
    "sealant_holders_closing_max" INTEGER NOT NULL,
    "sealant_injection_a_start_min" INTEGER NOT NULL,
    "sealant_injection_a_start_max" INTEGER NOT NULL,
    "sealant_injection_b_start_min" INTEGER NOT NULL,
    "sealant_injection_b_start_max" INTEGER NOT NULL,
    "sealant_injection_a_end_min" INTEGER NOT NULL,
    "sealant_injection_a_end_max" INTEGER NOT NULL,
    "sealant_injection_b_end_min" INTEGER NOT NULL,
    "sealant_injection_b_end_max" INTEGER NOT NULL,
    "sealant_injection_tube_orientation_start_min" INTEGER NOT NULL,
    "sealant_injection_tube_orientation_start_max" INTEGER NOT NULL,
    "sealant_injection_tube_orientation_end_min" INTEGER NOT NULL,
    "sealant_injection_tube_orientation_end_max" INTEGER NOT NULL,
    "sealant_latex_ring_padding_min" INTEGER NOT NULL,
    "sealant_latex_ring_padding_max" INTEGER NOT NULL,
    "sealant_latex_ring_width_min" INTEGER NOT NULL,
    "sealant_latex_ring_width_max" INTEGER NOT NULL,
    "sealant_tube_rigidity_min" INTEGER NOT NULL,
    "sealant_tube_rigidity_max" INTEGER NOT NULL,
    "sealant_cap_unscrewing_torque_min" INTEGER NOT NULL,
    "sealant_cap_unscrewing_torque_max" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tresholds_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "tresholds" ADD CONSTRAINT "tresholds_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tresholds" ADD CONSTRAINT "tresholds_conveyor_id_fkey" FOREIGN KEY ("conveyor_id") REFERENCES "conveyors"("id") ON DELETE CASCADE ON UPDATE CASCADE;
