import { JSONSchemaType } from "ajv";
import * as z from "zod";
import { TresholdUploadDataRow } from "./types";

const MAX_UPLOAD_SIZE = 1024 * 1024 * 3; // 3MB
export const ACCEPTED_FILE_TYPES = [
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.ms-excel",
];

export const uploadTresholdsFormSchema = z.object({
  file: z
    .instanceof(File, { message: "Необходимо выбрать файл" })
    .refine((file) => {
      return file.size <= MAX_UPLOAD_SIZE;
    }, `Max file size is 3MB.`)
    .refine((file) => {
      return ACCEPTED_FILE_TYPES.includes(file.type);
    }, "Only .png and .jpeg formats are accepted."),
});

export type UploadTresholdsFormValues = z.infer<
  typeof uploadTresholdsFormSchema
>;

export const tresholdsValidationSchema: JSONSchemaType<TresholdUploadDataRow> =
  {
    type: "object",

    properties: {
      conveyor_name: { type: "string" },
      code1C: {
        type: "string",
        pattern: "^[0-9]{1,6}$",
        errorMessage: { pattern: "Код 1С должен быть шестизначным числом" },
      },
      product_marking: {
        type: "string",
        minLength: 1,
        maxLength: 50,
        errorMessage: {
          minLength: "Артикул должен содержать хотя бы один символ",
          maxLength: "Длина артикула не должна быть больше 50 символов",
          type: "",
        },
      },
      product_name: { type: "string" },
      design: { type: "string" },
      extrusion_press_speed_min: { type: "string" },
      extrusion_press_speed_max: { type: "string" },
      extrusion_blow_time_min: { type: "string" },
      extrusion_blow_time_max: { type: "string" },
      extrusion_turning_machine_speed_min: { type: "string" },
      extrusion_turning_machine_speed_max: { type: "string" },
      extrusion_annealing_furnace_temp_min: { type: "string" },
      extrusion_annealing_furnace_temp_max: { type: "string" },
      extrusion_tube_cylindrical_section_length_min: { type: "string" },
      extrusion_tube_cylindrical_section_length_max: { type: "string" },
      extrusion_membrane_thickness_min: { type: "string" },
      extrusion_membrane_thickness_max: { type: "string" },
      extrusion_tube_diameter_min: { type: "string" },
      extrusion_tube_diameter_max: { type: "string" },
      extrusion_tube_cylindrical_section_thickness_min: { type: "string" },
      extrusion_tube_cylindrical_section_thickness_max: { type: "string" },
      extrusion_tube_rigidity_min: { type: "string" },
      extrusion_tube_rigidity_max: { type: "string" },
      extrusion_tube_cutting_quality: { type: "string" },
      extrusion_external_thread_quality: { type: "string" },
      extrusion_marking_quality: { type: "string" },
      extrusion_external_thread_value: { type: "string" },
      first_empty_field: { type: "string" },
      varnish_varnish_machine_speed_min: { type: "string" },
      varnish_varnish_machine_speed_max: { type: "string" },
      varnish_total_air_pressure_min: { type: "string" },
      varnish_total_air_pressure_max: { type: "string" },
      varnish_feed_can_air_pressure_min: { type: "string" },
      varnish_feed_can_air_pressure_max: { type: "string" },
      varnish_nozzle_regulator_air_pressure_min: { type: "string" },
      varnish_nozzle_regulator_air_pressure_max: { type: "string" },
      varnish_cells_speed_min: { type: "string" },
      varnish_cells_speed_max: { type: "string" },
      varnish_injection_a_start_position_min: { type: "string" },
      varnish_injection_a_start_position_max: { type: "string" },
      varnish_injection_b_start_position_min: { type: "string" },
      varnish_injection_b_start_position_max: { type: "string" },
      varnish_injection_c_start_position_min: { type: "string" },
      varnish_injection_c_start_position_max: { type: "string" },
      varnish_injection_d_start_position_min: { type: "string" },
      varnish_injection_d_start_position_max: { type: "string" },
      varnish_injection_a_end_position_min: { type: "string" },
      varnish_injection_a_end_position_max: { type: "string" },
      varnish_injection_b_end_position_min: { type: "string" },
      varnish_injection_b_end_position_max: { type: "string" },
      varnish_injection_c_end_position_min: { type: "string" },
      varnish_injection_c_end_position_max: { type: "string" },
      varnish_injection_d_end_position_min: { type: "string" },
      varnish_injection_d_end_position_max: { type: "string" },
      varnish_tube_molding_start_position_min: { type: "string" },
      varnish_tube_molding_start_position_max: { type: "string" },
      varnish_tube_molding_end_position_min: { type: "string" },
      varnish_tube_molding_end_position_max: { type: "string" },
      varnish_polimerization_furnace_temp_min: { type: "string" },
      varnish_polimerization_furnace_temp_max: { type: "string" },
      varnish_internal_varnish_porosity_min: { type: "string" },
      varnish_internal_varnish_porosity_max: { type: "string" },
      varnish_internal_sectional_view: { type: "string" },
      varnish_aluminium_clearance_lack: { type: "string" },
      varnish_unpainting_lack: { type: "string" },
      second_empty_field: { type: "string" },
      offset_printing_machine_speed_min: { type: "string" },
      offset_printing_machine_speed_max: { type: "string" },
      offset_total_air_pressure_min: { type: "string" },
      offset_total_air_pressure_max: { type: "string" },
      offset_padding_furnace_temp_min: { type: "string" },
      offset_padding_furnace_temp_max: { type: "string" },
      offset_offset_furnace_temp_min: { type: "string" },
      offset_offset_furnace_temp_max: { type: "string" },
      offset_printer_motor_min: { type: "string" },
      offset_printer_motor_max: { type: "string" },
      offset_base_covers_holders_motor_min: { type: "string" },
      offset_base_covers_holders_motor_max: { type: "string" },
      offset_base_covers_station_motor_min: { type: "string" },
      offset_base_covers_station_motor_max: { type: "string" },
      offset_imprint_quantity_printed_box_1_min: { type: "string" },
      offset_imprint_quantity_printed_box_1_max: { type: "string" },
      offset_imprint_quantity_printed_box_2_min: { type: "string" },
      offset_imprint_quantity_printed_box_2_max: { type: "string" },
      offset_imprint_quantity_printed_box_3_min: { type: "string" },
      offset_imprint_quantity_printed_box_3_max: { type: "string" },
      offset_imprint_quantity_printed_box_4_min: { type: "string" },
      offset_imprint_quantity_printed_box_4_max: { type: "string" },
      offset_imprint_quantity_printed_box_5_min: { type: "string" },
      offset_imprint_quantity_printed_box_5_max: { type: "string" },
      offset_imprint_quantity_printed_box_6_min: { type: "string" },
      offset_imprint_quantity_printed_box_6_max: { type: "string" },
      offset_ink_supply_time_min: { type: "string" },
      offset_ink_supply_time_max: { type: "string" },
      offset_design_match: { type: "string" },
      offset_tube_appearance: { type: "string" },
      offset_tube_edge_deformation_lack: { type: "string" },
      offset_aluminium_clearance_lack: { type: "string" },
      offset_drips_lack: { type: "string" },
      third_empty_field: { type: "string" },
      sealant_cap_machine_speed_min: { type: "string" },
      sealant_cap_machine_speed_max: { type: "string" },
      sealant_total_air_pressure_min: { type: "string" },
      sealant_total_air_pressure_max: { type: "string" },
      sealant_holders_forward_min: { type: "string" },
      sealant_holders_forward_max: { type: "string" },
      sealant_holders_opening_left_min: { type: "string" },
      sealant_holders_opening_left_max: { type: "string" },
      sealant_holders_opening_right_min: { type: "string" },
      sealant_holders_opening_right_max: { type: "string" },
      sealant_holders_closing_min: { type: "string" },
      sealant_holders_closing_max: { type: "string" },
      sealant_injection_a_start_min: { type: "string" },
      sealant_injection_a_start_max: { type: "string" },
      sealant_injection_b_start_min: { type: "string" },
      sealant_injection_b_start_max: { type: "string" },
      sealant_injection_a_end_min: { type: "string" },
      sealant_injection_a_end_max: { type: "string" },
      sealant_injection_b_end_min: { type: "string" },
      sealant_injection_b_end_max: { type: "string" },
      sealant_injection_tube_orientation_start_min: { type: "string" },
      sealant_injection_tube_orientation_start_max: { type: "string" },
      sealant_injection_tube_orientation_end_min: { type: "string" },
      sealant_injection_tube_orientation_end_max: { type: "string" },
      sealant_is_cap_surface_smooth: { type: "string" },
      sealant_latex_ring_padding_min: { type: "string" },
      sealant_latex_ring_padding_max: { type: "string" },
      sealant_latex_ring_width_min: { type: "string" },
      sealant_latex_ring_width_max: { type: "string" },
      sealant_tube_rigidity_min: { type: "string" },
      sealant_tube_rigidity_max: { type: "string" },
      sealant_cap_unscrewing_torque_min: { type: "string" },
      sealant_cap_unscrewing_torque_max: { type: "string" },
      fourth_empty_field: { type: "string" },
    },
    required: [
      "conveyor_name",
      "code1C",
      "product_marking",
      "product_name",
      "design",
      "extrusion_press_speed_min",
      "extrusion_press_speed_max",
      "extrusion_blow_time_min",
      "extrusion_blow_time_max",
      "extrusion_turning_machine_speed_min",
      "extrusion_turning_machine_speed_max",
      "extrusion_annealing_furnace_temp_min",
      "extrusion_annealing_furnace_temp_max",
      "extrusion_tube_cylindrical_section_length_min",
      "extrusion_tube_cylindrical_section_length_max",
      "extrusion_membrane_thickness_min",
      "extrusion_membrane_thickness_max",
      "extrusion_tube_diameter_min",
      "extrusion_tube_diameter_max",
      "extrusion_tube_cylindrical_section_thickness_min",
      "extrusion_tube_cylindrical_section_thickness_max",
      "extrusion_tube_rigidity_min",
      "extrusion_tube_rigidity_max",
      "extrusion_tube_cutting_quality",
      "extrusion_external_thread_quality",
      "extrusion_marking_quality",
      "extrusion_external_thread_value",
      // "first_empty_field",
      "varnish_varnish_machine_speed_min",
      "varnish_varnish_machine_speed_max",
      "varnish_total_air_pressure_min",
      "varnish_total_air_pressure_max",
      "varnish_feed_can_air_pressure_min",
      "varnish_feed_can_air_pressure_max",
      "varnish_nozzle_regulator_air_pressure_min",
      "varnish_nozzle_regulator_air_pressure_max",
      "varnish_cells_speed_min",
      "varnish_cells_speed_max",
      "varnish_injection_a_start_position_min",
      "varnish_injection_a_start_position_max",
      "varnish_injection_b_start_position_min",
      "varnish_injection_b_start_position_max",
      "varnish_injection_c_start_position_min",
      "varnish_injection_c_start_position_max",
      "varnish_injection_d_start_position_min",
      "varnish_injection_d_start_position_max",
      "varnish_injection_a_end_position_min",
      "varnish_injection_a_end_position_max",
      "varnish_injection_b_end_position_min",
      "varnish_injection_b_end_position_max",
      "varnish_injection_c_end_position_min",
      "varnish_injection_c_end_position_max",
      "varnish_injection_d_end_position_min",
      "varnish_injection_d_end_position_max",
      "varnish_tube_molding_start_position_min",
      "varnish_tube_molding_start_position_max",
      "varnish_tube_molding_end_position_min",
      "varnish_tube_molding_end_position_max",
      "varnish_polimerization_furnace_temp_min",
      "varnish_polimerization_furnace_temp_max",
      "varnish_internal_varnish_porosity_min",
      "varnish_internal_varnish_porosity_max",
      "varnish_internal_sectional_view",
      "varnish_aluminium_clearance_lack",
      "varnish_unpainting_lack",
      // "second_empty_field",
      "offset_printing_machine_speed_min",
      "offset_printing_machine_speed_max",
      "offset_total_air_pressure_min",
      "offset_total_air_pressure_max",
      "offset_padding_furnace_temp_min",
      "offset_padding_furnace_temp_max",
      "offset_offset_furnace_temp_min",
      "offset_offset_furnace_temp_max",
      "offset_printer_motor_min",
      "offset_printer_motor_max",
      "offset_base_covers_holders_motor_min",
      "offset_base_covers_holders_motor_max",
      "offset_base_covers_station_motor_min",
      "offset_base_covers_station_motor_max",
      "offset_imprint_quantity_printed_box_1_min",
      "offset_imprint_quantity_printed_box_1_max",
      "offset_imprint_quantity_printed_box_2_min",
      "offset_imprint_quantity_printed_box_2_max",
      "offset_imprint_quantity_printed_box_3_min",
      "offset_imprint_quantity_printed_box_3_max",
      "offset_imprint_quantity_printed_box_4_min",
      "offset_imprint_quantity_printed_box_4_max",
      "offset_imprint_quantity_printed_box_5_min",
      "offset_imprint_quantity_printed_box_5_max",
      "offset_imprint_quantity_printed_box_6_min",
      "offset_imprint_quantity_printed_box_6_max",
      "offset_ink_supply_time_min",
      "offset_ink_supply_time_max",
      "offset_design_match",
      "offset_tube_appearance",
      "offset_tube_edge_deformation_lack",
      "offset_aluminium_clearance_lack",
      "offset_drips_lack",
      // "third_empty_field",
      "sealant_cap_machine_speed_min",
      "sealant_cap_machine_speed_max",
      "sealant_total_air_pressure_min",
      "sealant_total_air_pressure_max",
      "sealant_holders_forward_min",
      "sealant_holders_forward_max",
      "sealant_holders_opening_left_min",
      "sealant_holders_opening_left_max",
      "sealant_holders_opening_right_min",
      "sealant_holders_opening_right_max",
      "sealant_holders_closing_min",
      "sealant_holders_closing_max",
      "sealant_injection_a_start_min",
      "sealant_injection_a_start_max",
      "sealant_injection_b_start_min",
      "sealant_injection_b_start_max",
      "sealant_injection_a_end_min",
      "sealant_injection_a_end_max",
      "sealant_injection_b_end_min",
      "sealant_injection_b_end_max",
      "sealant_injection_tube_orientation_start_min",
      "sealant_injection_tube_orientation_start_max",
      "sealant_injection_tube_orientation_end_min",
      "sealant_injection_tube_orientation_end_max",
      "sealant_is_cap_surface_smooth",
      "sealant_latex_ring_padding_min",
      "sealant_latex_ring_padding_max",
      "sealant_latex_ring_width_min",
      "sealant_latex_ring_width_max",
      "sealant_tube_rigidity_min",
      "sealant_tube_rigidity_max",
      "sealant_cap_unscrewing_torque_min",
      "sealant_cap_unscrewing_torque_max",
      // "fourth_empty_field",
    ],
    additionalProperties: false,
  };
