export enum ParameterUnits {
  COUNTER_VALUE = "шт",
  EXTRUSION_PRESS_SPEED = "шт/мин",
  EXTRUSION_BLOW_TIME = "мс",
  EXTRUSION_TURNING_MACHINE_SPEED = "шт/мин",
  EXTRUSION_ANNEALING_FURNACE_TEMP = "°С",
  EXTRUSION_TUBE_CILINDRICAL_SECTION_LENGTH = "мм",
  EXTRUSION_MEMBRANE_THIKNESS = "мм",
  EXTRUSION_TUBE_DIAMETER = "мм",
  EXTRUSION_TUBE_CILINDRICAL_THICKNESS = "мм",
  EXTRUSION_TUBE_RIGIDITY = "мм",
  //   EXTRUSION_TUBE_CUTTING_QUALITY = "Качество обрезки тубы", //boolean
  //   EXTRUSION_TIGHTNESS = "Герметичность",//boolean
  //   EXTRUSION_RONDEL_TYPE = "Тип рондоли",//boolean
  //   EXTRUSION_EXTERNAL_THREAD_QUALITY = "Внешняя резьба",//boolean

  VARNISH_VARNISH_MACHINE_SPEED = "шт/мин",
  VARNISH_TOTAL_AIR_PRESSURE = "Бар", //float
  VARNISH_FEED_CAN_AIR_PRESSURE = "Бар", //float
  VARNISH_NOZZLE_REGULATOR_AIR_PRESSURE = "Бар", //float
  VARNISH_CELLS_SPEED = "RPM", //RPM
  VARNISH_INJECTION_A_START_POSITION = "ед.", //ед.
  VARNISH_INJECTION_B_START_POSITION = "ед.", //ед.
  VARNISH_INJECTION_C_START_POSITION = "ед.", //ед.
  VARNISH_INJECTION_D_START_POSITION = "ед.", //ед.
  VARNISH_INJECTION_A_END_POSITION = "ед.", //ед.
  VARNISH_INJECTION_B_END_POSITION = "ед.", //ед.
  VARNISH_INJECTION_C_END_POSITION = "ед.", //ед.
  VARNISH_INJECTION_D_END_POSITION = "ед.", //ед.
  VARNISH_TUBE_MOLDING_START_POSITION = "ед.", //ед.
  VARNISH_TUBE_MOLDING_END_POSITION = "ед.", // ед.
  VARNISH_POLIMERIZATION_FURNACE_TEMP = "°С",
  VARNISH_INTERNAL_VARNISH_POROSITY = "mA", //boolean 0-15??
  // VARNISH_INTERNAL_SECTIONAL_VIEW = "Внутренний вид тубы в разрезе, качество покрытия", //boolean
  // VARNISH_ALUMINIUM_CLEARANCE_LACK = "Отсутствие просветов алюминия", //boolean
  // VARNISH_UNPAINTING_LACK = "Отсутствие непрокрасов и пятен", //boolean

  OFFSET_PRINTING_MACHINE_SPEED = "шт/мин",
  OFFSET_TOTAL_AIR_PRESSURE = "Бар", //float
  OFFSET_PADDING_FURNACE_TEMP = "°С",
  OFFSET_OFFSET_FURNACE_TEMP = "°С",
  OFFSET_PRINTER_MOTOR = "RPM",
  OFFSET_BASE_COVERS_HOLDERS_MOTOR = "RPM",
  OFFSET_BASE_COVERS_STATION_MOTOR = "RPM",
  OFFSET_IMPRINT_QUANTITY_PRINTED_BOX_1 = "отпечатков", //not required
  OFFSET_IMPRINT_QUANTITY_PRINTED_BOX_2 = "отпечатков", //not required
  OFFSET_IMPRINT_QUANTITY_PRINTED_BOX_3 = "отпечатков", //not required
  OFFSET_IMPRINT_QUANTITY_PRINTED_BOX_4 = "отпечатков", //not required
  OFFSET_IMPRINT_QUANTITY_PRINTED_BOX_5 = "отпечатков", //not required
  OFFSET_IMPRINT_QUANTITY_PRINTED_BOX_6 = "отпечатков", //not required
  OFFSET_INK_SUPPLY_TIME = "c", // decimal
  // OFFSET_DESIGN_MATCH = "Соответсвие дизайну и контрольному образцу", //boolean
  // OFFSET_TUBE_APPEARANCE = "Внешний вид тубы (разнотон, нечеткий текст, двоение печати)", //boolean
  // OFFSET_TUBE_EDGE_DEFORMATION_LACK = "Отсутствие деформации края тубы", //boolean
  // OFFSET_ALUMINIUM_CLEARANCE_LACK = "Отсутствие просветов алюминия", //boolean
  // OFFSET_DRIPS_LACK = "Отсутствие марашек", //boolean

  SEALANT_CAP_MACHINE_SPEED = "шт/мин",
  SEALANT_TOTAL_AIR_PRESSURE = "Бар", //float
  SEALANT_HOLDERS_FORWARD = "ед.", //ед.
  SEALANT_HOLDERS_OPENING_LEFT = "ед.", //ед.
  SEALANT_HOLDERS_OPENING_RIGHT = "ед.", //ед.
  SEALANT_HOLDER_CLOSING = "ед.", //ед.
  // SEALANT_INJECTION_A_START = "Начало впрыска А", Ед??
  // SEALANT_INJECTION_B_START = "Начало впрыска B",
  // SEALANT_INJECTION_A_END = "Конец впрыска А",
  // SEALANT_INJECTION_B_END = "Конец впрыска B",
  // SEALANT_INJECTION_TUBE_ORIENTATION_START = "Положение тубы для впрыска (начальное положение)",
  // SEALANT_INJECTION_TUBE_ORIENTATION_END = "Положение тубы для впрыска (конечное положение)",
  // SEALANT_IS_CAP_SURFACE_SMOOTH = "Поверхность колпачка гладкая, без царапин", //boolean
  SEALANT_LATEX_RING_PADDING = "мм",
  SEALANT_LATEX_RING_WIDTH = "мм",
  SEALANT_TUBE_RIGIDITY = "мм",
  SEALANT_CAP_UNSCREWING_TORQUE = "Н.см",
}
