# Dockerfile для nginx файлового сервера
FROM nginx:alpine

# Создаем директорию для файлов
RUN mkdir -p /usr/share/nginx/files

# Копируем конфигурацию nginx для файлового сервера
COPY nginx-file-server.conf /etc/nginx/conf.d/default.conf


# Устанавливаем права доступа
RUN chmod -R 755 /usr/share/nginx/files

# Открываем порт 8080
EXPOSE 8080

# Запускаем nginx
CMD ["nginx", "-g", "daemon off;"]