FROM node:20-slim AS builder

RUN apt-get update && apt-get install -y openssl python3 make g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json package-lock.json ./
COPY api_tubes/package.json ./api_tubes/

RUN npm ci -w api_tubes

COPY api_tubes/ ./api_tubes/

WORKDIR /app/api_tubes
RUN npx prisma generate
RUN npm run build

FROM node:20-slim AS runtime
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*


WORKDIR /app

ENV PATH="/app/node_modules/.bin:${PATH}"

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/api_tubes ./api_tubes

WORKDIR /app/api_tubes

EXPOSE 7100

CMD ["npm", "run", "start:migrate:prod"]