FROM node:20-alpine AS deps

RUN apk add --no-cache libc6-compat
WORKDIR /app


COPY package.json package-lock.json ./
COPY new-app/package.json ./new-app/

RUN npm ci -w new-app


FROM node:20-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY new-app ./new-app
COPY package.json ./ 

ARG NEXT_PUBLIC_API_URL
ARG INTERNAL_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV INTERNAL_API_URL=$INTERNAL_API_URL
ENV NEXT_TELEMETRY_DISABLED 1

WORKDIR /app/new-app
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/new-app/public ./new-app/public
COPY --from=builder --chown=nextjs:nodejs /app/new-app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/new-app/.next/static ./new-app/.next/static

USER nextjs

EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "new-app/server.js"]