FROM node:20-alpine AS deps
WORKDIR /new-app
COPY ./new-app/package*.json  ./
RUN npm ci

# 2. Stage: Сборка проекта
FROM node:20-alpine AS builder
WORKDIR /new-app
COPY --from=deps /new-app/node_modules ./node_modules
COPY . .
# Отключаем телеметрию Next.js во время сборки
ENV NEXT_TELEMETRY_DISABLED 1
RUN npm run build

# 3. Stage: Финальный образ (Runner)
FROM node:20-alpine AS runner
WORKDIR /new-app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

# Создаем пользователя для безопасности
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Копируем только необходимые файлы из builder
COPY --from=builder /new-app/public ./public
COPY --from=builder --chown=nextjs:nodejs /new-app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /new-app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT 3000

CMD ["node", "server.js"]


