name: Release & Versioning

on:
  push:
    branches: [release]

jobs:
  bump-and-tag:
    # Проверка [skip ci], чтобы GitHub Actions не запускал сам себя после пуша версии
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version
        # Добавляем сообщение коммита с [skip ci], чтобы избежать бесконечного цикла
        run: |
          npm version patch --include-workspace-root --workspaces -m "chore: bump version to %s [skip ci]"

      - name: Push Changes & Tags to Release
        run: |
          # Пушим коммит и тег в ветку release
          git push origin release --follow-tags

      - name: Sync version to Main
        run: |
          git fetch origin main
          git checkout main
          
          # Если main ушел вперед, --ff-only упадет. 
          # Используем обычный merge, чтобы просто забрать версию.
          git merge release -m "chore: sync version from release [skip ci]"
          
          git push origin main
