name: Release, Sync & Build Docker

on:
  push:
    branches: [release]

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  bump-sync-and-build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_GITHUB_PAT }}

      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 1. Обновляем версию в package.json монорепозитория
      - name: Bump & Push to Release
        run: |
          npm version patch --include-workspace-root --workspaces -m "chore: release %s [skip ci]"
          git push origin release --follow-tags

      # 2. Собираем универсальные Docker-образы
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Monorepo Images
        run: |
          IMAGE_OWNER=$(echo "${{ env.OWNER }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_REPO=$(echo "${{ env.REPO_NAME }}" | tr '[:upper:]' '[:lower:]')

          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1

          # Подставляем переменные из вашего примера .env для сборки new_app
          export NEXT_PUBLIC_API_URL="/api/tubes"
          export INTERNAL_API_URL="http://tubes_api:7100/api_tubes"

          # Запускаем сборку всех 6 образов
          docker compose -p monorepo -f docker-compose.build.yml build

          # Список сервисов в точности как в файле docker-compose.build.yml
          SERVICES="tubes_api public_api new_app tubes_dash nginx nginx-file-server"

          for svc in $SERVICES; do
            docker tag monorepo-${svc} ghcr.io/$IMAGE_OWNER/$IMAGE_REPO/${svc}:latest
            docker push ghcr.io/$IMAGE_OWNER/$IMAGE_REPO/${svc}:latest
          done

      # 3. Синхронизируем обновленные package.json назад в main
      - name: Sync version to Main
        run: |
          # 👇 Принудительно уничтожаем любые изменения файлов на диске раннера
          git reset --hard HEAD
          git clean -fd

          # Скачиваем актуальное состояние удаленного репозитория
          git fetch origin main

          # Теперь переключение гарантированно пройдет без ошибок
          git checkout main

          # Сливаем изменения версий из релизной ветки
          git merge release --no-edit

          # Отправляем обновленный main в GitHub
          git push origin main
